ciphering files, so you don't need to have a specific conf in apache to not read the content of the res dir

diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,6 +1,7 @@
 #!/bin/bash
 
-host="https://lorem.jim.netnix.in/share/"
+#host="https://lorem.jim.netnix.in/share/"
+host="https://share.jim.netnix.in/"
 
 
 a="$(date)"
@@ -23,4 +24,25 @@ if [ "$a" != "$b" ];then
 	printf "%s != %s\n" "$a" "$b" 
 	exit 1
 fi
-echo "ok"
+if [ -f test.bin ] || [ -f res.bin ] ;then
+	printf "Cannot test everything, there is a test.bin or a res.bin file that i don't dare to erase\n"
+	exit 1
+fi
+dd if=/dev/random of=test.bin bs=1048 count=10 2> /dev/null
+
+url=$(cat test.bin | curl -s -F data=@- -F 'duration=1' $host"share.php")
+curl -s "$url" > res.bin
+if ! diff res.bin test.bin;then
+	echo "it fails on a binary file, i'll leave test.bin and res.bin for you to check"
+	ok=0
+else
+	ok=1
+fi
+
+if [ $ok -eq 1 ];then
+	rm test.bin res.bin
+	echo "ok"
+	exit 0
+else
+	exit 1
+fi
